Dockerfile, README.md, config.js, package.json, test/examples/deviceProvisioning/deviceProvisioningNoMapping.json, test/examples/deviceProvisioning/deviceProvisioningPluginMapping.json, test/examples/deviceProvisioning/deviceProvisioningRightMapping.json, test/unit/deviceProvisioning-test.js, test/unit/ngsi-communication-test.js
=> ADD Docker file and upgrade version

CHANGES_NEXT_RELEASE, README.md, bin/iotagent.js, config.js, lib/configService.js, lib/iotagentCore.js, lib/sigfoxHandlers.js, lib/sigfoxServer.js, package.json, test/testConfig.js, test/unit/deviceProvisioning-test.js, test/unit/ngsi-communication-test.js, test/unit/plugin-config-test.js
Update to last version of iotagent-node-lib in order to allow use env variables.
Update config and logger system.
=> update iotagent node library dependence

CHANGES_NEXT_RELEASE, package.json
align deps versions with iotajson and iotaul:
- request 2.81.0
- async 1.5.2
- express ~4.11.2
=> [WIP] upgrade request and async deps

CHANGES_NEXT_RELEASE, rpm/SOURCES/etc/cron.d/cron-logrotate-iotasigfox-size, rpm/SOURCES/etc/init.d/iotasigfox, rpm/SOURCES/etc/iotajson.d/iotasigfox.default.conf, rpm/SOURCES/etc/logrotate.d/logrotate-iotasigfox.conf, rpm/SOURCES/etc/sysconfig/iotasigfox.conf, rpm/SOURCES/etc/sysconfig/logrotate-iotasigfox-size
issue https://github.com/telefonicaid/sigfox-iotagent/issues/6
=> add service files

CHANGES_NEXT_RELEASE, Dockerfile
Based in PR https://github.com/telefonicaid/iotagent-json/pull/337
=> Use pm2 in Dockerfile

package.json
=> Step: 1.1.0 -> 1.1.0-next

README.md
Also: **[SHOULD] Repo description, topics and URL link**
Please click the edit button at the head of the repo and amend the description link and topics as shown (or similar):
> https://iotagent-sigfox.rtfd.io/
`fiware`, `iot`, `iot-agent`
- SHOULD requirement from the TSC.
=>  Add Documentation badge and link box

docker/Dockerfile
Sigfox Equivalent of https://github.com/telefonicaid/iotagent-ul/pull/342
=> Expose Ports

.prettierrc.json, bin/sigfox-test.js, lib/iotagentCore.js, lib/sigfoxHandlers.js, lib/sigfoxServer.js, test/tools/ngsiUtils.js, test/unit/deviceProvisioning-test.js, test/unit/plugin-config-test.js, test/unit/sigfox-parser-test.js
Related to https://github.com/telefonicaid/iotagent-json/pull/377#discussion_r259458150
=> Amend prettier config to 120 width.

config.js, docker/Dockerfile, docker/README.md, docker/entrypoint.sh, docker/hooks/build
Port over Docker Secrets support
see:  https://github.com/telefonicaid/iotagent-json/pull/390
=> Fix #46 - Add docker secrets

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotasigfox.spec
=> Step: 1.1.0-next -> 1.2.0

CHANGES_NEXT_RELEASE, bin/iotagent-sigfox, bin/sigfox-test.js, config.js, docker/README.md, docs/installationguide.md, docs/limits.conf, docs/sysctl.conf, lib/errors.js, lib/sigfoxHandlers.js, package.json, test/unit/requiredFields-test.js
@fgalan
- Modify the Sigfox IoT Agent to deal with the option multi-thread.
- Add the corresponding new variable in the config.js (multiCore) with description.
- Change in the Readme.md (Docker) and Administration Guide regarding High Performance execution of the Sigfox IoT Agent.
- Create 2 examples files of the user limits and sysctl configuration for high performance execution.
- Correct typos in doc files.
- Provide information of the Sigfox IoT Agent version in the request /iot/about.
- Improve the testing script (sigfox-test.js)
- Improve the information about mandatory fields not provided (errors.js & sigfoxHandlers.js).
- (Temporally) Update the package.json to link to the IoTAgent Node Lib with the changes for testing purposes. NEED TO BE REVERT when the PR #815 is merged.
Unit …
=> Update IoTA-Sigfox with the changes of the IoTA Node Lib related to multi-threading

CHANGES_NEXT_RELEASE, bin/iotagent-sigfox, bin/sigfox-test.js, config.js, docker/README.md, docs/installationguide.md, docs/limits.conf, docs/sysctl.conf, lib/errors.js, lib/sigfoxHandlers.js, package.json, test/unit/requiredFields-test.js
Continues PR #64. The docker image for CI e2e will be built from this branch.
CC: @flopezag @jason-fox
=> Update IoTA-Sigfox with the changes of the IoTA Node Lib related to multi-threading (final landing)

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotasigfox.spec
=> Step: 1.2.0-next -> 1.3.0

test/tools/utils.js
Related: https://github.com/telefonicaid/iotagent-node-lib/pull/812
=> Catch missing file failure and continue

docs/roadmap.md
=> Roadmap update

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotasigfox.spec
=> Step: 1.3.0-next -> 1.4.0

package.json, rpm/SPECS/iotasigfox.spec
=> Step: 1.4.0 -> 1.4.0-next

config.js
=> make use of IoT Agent Manager optional in config.js

package.json
Mimics PR https://github.com/telefonicaid/sigfox-iotagent/pull/79
=> Step 1.5.0 -> 1.5.0-next

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotasigfox.spec
=> Step: 1.5.0-next -> 1.6.0
